feat : basic CRUD App using Doobie/tranzactio
SHSongs/working-scala pull request #18
Opened 2023-08-05 06:00 UTC by darkenpeng

지난 주(7/30)에 페어 프로그래밍을 통해 진행되었던 `정규모임3`의 예제코드를 추가했습니다.

`최소 요구사항`
- 기본 CRUD
- user의 입력은 readline으로 처리

`추가한 부분`
- 입력을 case class - pattern match로 처리
- 입력 parse
- repository, service layer 분리
- DB connection 분리
- driver 수동으로 추가(d/t VSC에서만 발생하는 에러)

2023-08-05 08:27 UTC, SHSongs requested changes

2023-08-05 08:27 UTC, SHSongs commented on doobie-db/src/main/scala/DiaryService.scala
> +        }
이부분 실제로 작동 잘 되나요?

2023-08-05 08:27 UTC, SHSongs commented on doobie-db/src/main/scala/DiaryService.scala
> +        _ <- zio.Console.printLine(s"${targetNumber}번은 삭제되었습니다.")
scalafmt를 이용해 정렬 한번 해주시면 가독성이 더 좋아질 거 같습니다

2023-08-05 08:27 UTC, SHSongs commented on forecast-cheese/src/main/scala/ForecastClient.scala
주석처리한 코드는 과감히 삭제해주세요

2023-08-05 08:27 UTC, SHSongs commented on doobie-db/src/main/scala/MoodParser.scala
> +  }
정확한 점수로 기분을 입력받는다면(현재상태 유지) 입력받은 값이 프로그램의 예상과 다르다면 에러를 내는게 조금 더 나을 거 같습니다.

2023-08-08 13:11 UTC, darkenpeng commented on doobie-db/src/main/scala/DiaryService.scala
> +        }
아니요 작동하지 않아서 수정했습니다

2023-08-08 13:12 UTC, darkenpeng commented on forecast-cheese/src/main/scala/ForecastClient.scala
제가 작성하지 않은 코드여서 다시 주석 해제하겠습니다

2023-08-08 13:12 UTC, darkenpeng commented on doobie-db/src/main/scala/MoodParser.scala
> +  }
넵 ZIO.fail로 감싸겠습니다

2023-08-08 13:31 UTC, merged

2023-08-08 13:31 UTC, SHSongs commented
👍