for-comprehension 문서화
SHSongs/working-scala pull request #27
Opened 2023-08-28 12:17 UTC by hatchling13

## 개요
1. for-comprehension에 대한 이해를 돕기 위해 기본 Scala에서의 for-comprehension에 대한 설명을 추가하였습니다.
2. ZIO에서 for-comprehension을 사용할 수 있는 이유에 대한 설명을 추가하였습니다.
3. 간단한 예제 코드를 작성하였습니다.
4. 예제 코드에 대한 테스트 코드를 작성하였습니다.

## 주의사항
**for-comprehension은 언어 내장 기능이기 떄문에 별도의 메소드 설명이 필요하지 않다 생각하여 '메소드 목록' 란은 제외하였습니다.**

2023-09-04 13:49 UTC, SHSongs requested changes

2023-09-04 13:49 UTC, SHSongs commented on for-comprehension-in-zio/README.md
> +`ZIO` 타입은 `foreach`, `filter`, `map`, `flatMap` 함수를 모두 구현하고 있으며, 자세한 구현체는 [여기](https://github.com/zio/zio/blob/series/2.x/core/shared/src/main/scala/zio/ZIO.scala)서 확인할 수 있습니다. 각 함수들이 모두 구현되어있으므로, ZI
`구현하고 있으며`가 조금 애매한 거 같습니다. ZIO타입이 Iterable을 상속받아 flatMap을 구현한 것처럼 느껴지네요.

2023-09-04 13:50 UTC, SHSongs commented
Conflict 해결 부탁드립니다

2023-09-04 22:31 UTC, hatchling13 commented
Confilct 해결하였으며, 고차 함수 관련 서술을 수정하였습니다.

2023-09-05 13:36 UTC, SHSongs commented
이 문서는 ZIO의 flatMap을 설명하고 for-comprehension을 이용하면 편하게 이펙트를 실행할 수 있다고 말해주면 좋을 거 같습니다. 
그리고 Iterable의 for-comprehension 문서 만든 후 참고링크로 걸어주고요.
어떻게 생각하시나요?  @hatchling13

2023-09-05 20:57 UTC, hatchling13 commented
말씀해주신 방향으로 작업 진행해보겠습니다!

2023-09-10 14:48 UTC, SHSongs commented
👍

2023-09-10 14:48 UTC, merged