DB Connection 문서화
SHSongs/working-scala pull request #28
Opened 2023-08-29 17:38 UTC by Whis-dev

## 개요
DB Connection 문서화 작업 내용입니다.
예제 코드와 프로젝트에 대한 간단한 설명을 기입했습니다.

**지훈님과 함께 작업을 하고 있어, 작업이 완료되면 코멘트로 남기고 머지 요청 드리겠습니다**

2023-09-04 03:37 UTC, Whis-dev commented
@SHSongs 작업 완료되어 머지 요청드립니다! 예제 코드는 지훈님께서 작업해주셨고 리드미는 제가 작성했습니다. 참고 부탁드립니다!

2023-09-04 13:54 UTC, SHSongs requested changes

2023-09-04 13:54 UTC, SHSongs commented on db-connection/README.md
> +(postgresql 또는 sqlite)
코드에는 테이블을 생성해주는 함수가 없어 DB만 세팅하고 실행하면 테이블을 찾을 수 없다는 에러가 발생할 거 같습니다.
 어떤 테이블은 만들어야 할 지 스키마나 create sql을 작성해주면 좋을 거 같습니다

2023-09-04 13:54 UTC, SHSongs commented on db-connection/README.md
> +  - 현재 세팅은 postgresql기준으로 작성되어 있습니다. 만약 db를 sqlite로 변경하여 사용하고 싶은 경우 DBConnection.scala파일 31번째 줄의 postgres를 지우고, sqlite를 입력해주세요.
다른 환경에서 실행 방법이 자세히 나와있어 좋은 거 같습니다 👍

2023-09-04 13:54 UTC, SHSongs commented
Conflict 해결 부탁드립니다

2023-09-06 22:12 UTC, Whis-dev commented
@SHSongs 테이블생성 메소드 추가 및 컨플릭 해결하여 반영했습니다! 확인 부탁드립니다!

2023-09-07 12:08 UTC, SHSongs commented
👍

2023-09-07 12:08 UTC, merged