feat : Declarative programming example
SHSongs/working-scala pull request #29
Opened 2023-09-02 00:48 UTC by darkenpeng

2023-09-05 13:10 UTC, darkenpeng commented
@SHSongs 
README를 업데이트하고 리팩토링하였습니다.

2023-09-05 13:56 UTC, SHSongs requested changes

2023-09-05 13:56 UTC, SHSongs commented on declarative-prog/src/main/scala/Repository.scala
> +  def checkIfRestaurantExist(restaurant_id: String): ZIO[doobie.Database.Service, DbException, Boolean] = for {
restaurantId

2023-09-05 13:56 UTC, SHSongs commented on declarative-prog/src/main/scala/Main.scala
> +     }
main 함수에서는 판단하는 곳 없이 Controller를 순차적으로 실행만 하면 좋을 거 같은데 어떻게 생각하시나요?

2023-09-05 14:06 UTC, darkenpeng commented on declarative-prog/src/main/scala/Main.scala
> +     }
저도 Main이 실행만 하는 부분으로 분리되지 않아 고민했었습니다
하나의 동작이 여러 개의 메서드로 이루어져 있어 하나의 레이어에서 여러 개의 메서드가 호출되어도 흐름이 어색하지 않을 지 판단하기 어렵습니다

예를 들면 예약하기라는 하나의 동작에 Controller.showAllRestaurantToUser
Controller.selectReservationByNumber
Controller.registerReservation
이 메서드가 순서대로 호출되어야 합니다

하지만 Controller에서 이 세가지 메서드들을 모두 호출하는 새로운 함수를 정의하는 것은 역할이 불분명해보여서 고민입니다. 어떻게할까요?

2023-09-08 12:39 UTC, darkenpeng commented on declarative-prog/src/main/scala/Repository.scala
> +  def checkIfRestaurantExist(restaurant_id: String): ZIO[doobie.Database.Service, DbException, Boolean] = for {
수정하였습니다

2023-09-08 12:45 UTC, darkenpeng commented on declarative-prog/src/main/scala/Main.scala
> +     }
그럼 Controller에서 showAllRestaurantsToUser 와 selectRestaurantByNumber를 동시에 호출하는 함수를 생성해야 할까요?? 
유저인터페이스와 상호작용하는 부분이 main에 있기보단 Controller에 두는 것이 적절할 것 같다는 생각을 했었습니다.
하지만 하나의 함수와 여러 개의 함수를 묶은 함수를 같은 층위에 두는 게 맞을 지 고민됩니다

showAllRestaurantsToUser와 같은 함수를 Service단에 두기엔 내부에 유저인터페이스와 상호작용하는 부분이 포함되어 있어서 판단하기 어렵습니다

2023-09-10 12:10 UTC, SHSongs commented on declarative-prog/src/main/scala/Main.scala
> +     }
사용자의 action을 `예약하기`와 `예약변경` 또는 잘못된 액션을 판단하는 것 또한 저는 비지니스 로직이라 생각이 들어 Controller에서 하는게 나을거 같다는 생각이 들었습니다.

예를들어 Main이 사람이고 Controller가 키오스크라 할 때 키오스크에서 제일 처음에 포장과 매장식사라는 선택지가 있다고 합니다.
그런데 사람은 키오스크가 보여준 화면에서 선택을 하면 판단해 어떤 다음 화면을 보여줄지 판단하지 사람이 직접 다음 로직을 뭘 할지 직적 Controller를 호출하지는 않습니다.
정리하자면 저는 어떤 Controller를 호출할지 정하는 것조차 Controller의 일이라고 생각합니다

2023-09-12 03:59 UTC, darkenpeng commented on declarative-prog/src/main/scala/Main.scala
> +     }
@SHSongs
말씀해주신 대로 Main에 있던 유저와 상호작용하는 로직을 Controller로 이동시켰습니다.
+ scalafmt로 정렬 한 번 해주었습니다.

2023-09-13 23:38 UTC, SHSongs requested changes

2023-09-13 23:38 UTC, SHSongs commented on declarative-prog/declarative-programming.md
> +- getAction(): ZIO[Any,Serializable,String]
시그니처 업데이트가 필요합니다. READMe 관리가 힘들다면 trait을 만든 후 주석을 다는 방법도 있을 거 같아요

2023-09-13 23:38 UTC, SHSongs commented on declarative-prog/src/main/scala/Main.scala
> +  } yield ()
action을 실제로 실행해주는 부분이 없는 거 같은데 잘 실행 되나요?

2023-09-16 08:36 UTC, darkenpeng commented on declarative-prog/declarative-programming.md
> +- getAction(): ZIO[Any,Serializable,String]
멘토님 제가 리팩토링 할 때마다 시그니처를 수동으로 쓰는 것에 고통을 느껴서 sbt의 scaladoc에 대해 찾아보았습니다.
$ sbt scaladoc 
<img width="1079" alt="image" src="https://github.com/SHSongs/working-scala/assets/91370858/d10d34fe-0a6e-45b1-abd0-de0f5db413d8">

현재 html 파일로 생성된 상태인데 괜찮다하시면 로컬에 publish하는 방법을 알아보고 그걸 README.md에 적는 것도 좋을 것 같습니다. 어떻게 생각하시나요?

2023-09-16 08:36 UTC, darkenpeng commented on declarative-prog/src/main/scala/Main.scala
> +  } yield ()
앗 고쳤습니다

2023-09-16 08:59 UTC, darkenpeng commented
- [ ] 시그니처가 업데이트되어야 합니다.
- [ ] 쿠폰에 Cascade가 걸리지 않았습니다.(예약 변경 시 쿠폰의 할인율 변경)
- [ ] ADTs.scala에서 Coupon에 Reservation의 id가 추가되어야 합니다.

2023-09-16 13:21 UTC, SHSongs commented on declarative-prog/declarative-programming.md
> +- getAction(): ZIO[Any,Serializable,String]
좋은거 같습니다

2023-09-17 05:13 UTC, merged

2023-09-17 05:13 UTC, SHSongs commented
임시 머지