DI 한글화
SHSongs/working-scala pull request #32
Opened 2023-09-04 13:50 UTC by jihun315016

2023-09-04 14:00 UTC, SHSongs requested changes

2023-09-04 14:00 UTC, SHSongs commented on dependency-injection/dependency-injection.md
해당 예제는 무슨 이유로 DI를 활용하는지 설명해주면 좋을 거 같습니다

DITest1와 DITest2의 차이점을 설명해주면 좋을 거 같습니다.

2023-09-07 01:32 UTC, jihun315016 commented
문서 작성 완료했습니다.
혹시 부족하거나 잘못된 부분이 있다면 말씀해주시면 반영하겠습니다.

2023-09-07 12:05 UTC, SHSongs requested changes

2023-09-07 12:05 UTC, SHSongs commented on dependency-injection/dependency-injection.md
> +} yield ()
함수 시그니처에 작성된 `ZIO[R,E,A]`의 `R`타입과 사용하는 부분인 `ZIO.service[T]` 일치해야 한다는 의미 맞을까요?
`R`타입에 작성된 내용 외에 한번 식당 명확한 의미의 문장을 작성해보면 좋을 거 같습니다.  (http://www.weather.go.kr/wnuri_help/html/weather/impact-info.jsp 이쪽 링크의 단계 참고)
 
추가로 컴파일러는 R 과 T를 완전 다른 타입으로 인식해서 컴파일 에러가 발생할 거 같네요.

2023-09-15 14:50 UTC, SHSongs commented
👍

2023-09-15 14:50 UTC, merged