날씨 정보 웹훅 제작
SHSongs/working-scala pull request #7
Opened 2023-07-23 14:31 UTC by notJoon

## 요약

1. 날씨 API와 csv데이터를 이용해 디스코드 채널에 날씨 정보를 보내는 웹훅 코드 작성
2. 지역의 좌표를 이용해서 해당 동과 일치하도록 매핑 함수 작성
3. 날짜, 시간 포메팅 함수 작성

2023-07-24 11:59 UTC, SHSongs requested changes

2023-07-24 11:59 UTC, SHSongs commented on Forecast/src/main/scala/Forecast.scala
> +        ZIO.fromEither(response.body)
요청 보내는 부분을 `ZIO.attempt`로 감싸도 괜찮을 거 같네요 https://zio.dev/reference/core/zio/#from-side-effects

2023-07-24 11:59 UTC, SHSongs commented on Forecast/src/main/scala/Forecast.scala
> +    implicit val headerDecoder: HeaderDecoder[RegionData] = HeaderDecoder.decoder("격자 X", "격자 Y", "3단계")(RegionData.apply _)
`Header`를 implicit으로 사용하는 방법 관련 예제, 문서 링크나 설명을 찾아 주석을 달면 좋을 거 같습니다.

2023-07-24 11:59 UTC, SHSongs commented on Forecast/src/main/scala/Forecast.scala
> +        }).take(5))
take는 Iterable을 구현한 class가 사용할 수 있습니다. 
`val n = 2` 일 때 `List(1,2,3).take(n)` 이면 `List(1,2)`를 돌려줍니다. 
`n`이 음수거나 List Length보다 더 큰 경우는 전체 List를 돌려줍니다.

2023-07-25 02:13 UTC, notJoon commented on Forecast/src/main/scala/Forecast.scala
> +        }).take(5))
주석을 잘못 작성했네요 이 부분은 수정했습니다.

2023-07-25 03:40 UTC, notJoon commented on Forecast/src/main/scala/Forecast.scala
> +        ZIO.fromEither(response.body)
```scala
ZIO.attempt {
    val response: Identity[Response[Either[ResponseException[String, String], ResponsePayload]]] = ...
}.flatMap(ZIO.fromEither(_))
```
이렇게 `ZIO.attempt`로 묶었습니다. 또한 이 부분에 첨부해주신 링크를 레퍼런스로 넣음 주석을 추가했습니다.

2023-07-25 03:41 UTC, notJoon commented on Forecast/src/main/scala/Forecast.scala
> +    implicit val headerDecoder: HeaderDecoder[RegionData] = HeaderDecoder.decoder("격자 X", "격자 Y", "3단계")(RegionData.apply _)
```scala
// 지역 정보를 CSV 파일에서 읽어오기 위한 Decoder입니다.
object RegionData {
    // `implicit` 키워드를 사용하여 `HeaderDecoder` 타입의 implicit 변수를 선언하였습니다. 이를 통해 필요한 경우 컴파일러가 자동으로 이 디코더를 찾아 사용할 수 있습니다.
    //
    // 이 변수는 `kantan.csv` 라이브러리가 CSV 파일을 `RegionData` 객체로 디코딩하는 데 사용됩니다.
    // 하지만 `implicit`를 사용했기 때문에 `RegionData` 객체를 직접 디코딩하는 코드를 작성하지 않아도 컴파일러가 알아서 적절한 디코딩 로직을 찾아 사용하게 됩니다.
    //
    // `implicit`은 변환기(converter), 매개변수 값 주입기(parameter value injector), 확장 메서드(extension method) 등의 역할을 할 수 있습니다.
    // 여기서는 매개변수 값 주입기의 역할을 하며, 컴파일러가 필요한 매개변수를 찾을 때 이 `implicit` 값을 사용하게 됩니다.
    //
    // ref: https://stackoverflow.com/questions/10375633/understanding-implicit-in-scala
    implicit val headerDecoder: HeaderDecoder[RegionData] = HeaderDecoder.decoder("격자 X", "격자 Y", "3단계")(RegionData.apply _)
}
```
`implicit`을 이용한 목적과 관련 자료를 주석에 추가했습니다.

2023-07-25 10:47 UTC, merged

2023-07-25 10:47 UTC, SHSongs commented
👍